<?php

return [
    'order_number_prefix' => 'CLR',

    'payment' => [
        'vietqr' => [
            'image_base_url' => env('VIETQR_IMAGE_BASE_URL', 'https://img.vietqr.io/image'),
            'bank_id' => env('VIETQR_BANK_ID', '970407'),
            'account_number' => env('VIETQR_BANK_ACCOUNT', '2005111818'),
            'account_name' => env('VIETQR_ACCOUNT_NAME', 'DO TRUNG QUAN'),
            'template' => env('VIETQR_TEMPLATE', '4ueHdQu'),
        ],
    ],

    'payment_methods' => [
        'cod' => [
            'label' => 'Thanh toán khi nhận hàng',
            'short_label' => 'COD',
            'description' => 'Thanh toán trực tiếp khi đơn được giao đến bạn.',
            'provider' => 'cod',
            'initial_status' => 'unpaid',
            'requires_vietqr' => false,
            'is_simulated' => false,
            'confirmation_title' => 'Thanh toán khi đơn được giao.',
            'confirmation_description' => 'Vui lòng chuẩn bị đúng tổng tiền khi nhận hàng.',
        ],
        'bank_transfer' => [
            'label' => 'Chuyển khoản qua VietQR',
            'short_label' => 'VietQR',
            'description' => 'Quét mã QR đúng số tiền và nội dung chuyển khoản sau khi đặt đơn.',
            'provider' => 'vietqr',
            'initial_status' => 'pending',
            'requires_vietqr' => true,
            'is_simulated' => false,
            'confirmation_title' => 'Quét mã để thanh toán.',
            'confirmation_description' => 'Đơn sẽ chờ đối soát trước khi được xác nhận thanh toán.',
        ],
        'momo' => [
            'label' => 'Ví MoMo',
            'short_label' => 'MoMo',
            'description' => 'Thanh toán bằng ví MoMo sau khi cổng thanh toán được kết nối.',
            'provider' => 'momo',
            'initial_status' => 'pending',
            'requires_vietqr' => false,
            'is_simulated' => true,
            'confirmation_title' => 'Đang chờ khởi tạo thanh toán MoMo.',
            'confirmation_description' => 'Clare đã ghi nhận lựa chọn của bạn. Liên kết thanh toán MoMo sẽ chỉ được tạo khi cổng thanh toán được kết nối.',
        ],
        'bank_card' => [
            'label' => 'Thẻ ngân hàng',
            'short_label' => 'Thẻ',
            'description' => 'Thanh toán bằng thẻ ATM nội địa hoặc thẻ quốc tế qua cổng bảo mật.',
            'provider' => 'bank_card_gateway',
            'initial_status' => 'pending',
            'requires_vietqr' => false,
            'is_simulated' => true,
            'confirmation_title' => 'Đang chờ khởi tạo thanh toán thẻ.',
            'confirmation_description' => 'Clare không lưu số thẻ. Cổng thanh toán bảo mật sẽ được mở khi kết nối gateway hoàn tất.',
        ],
        'pay_later' => [
            'label' => 'Mua trước, trả sau',
            'short_label' => 'Trả sau',
            'description' => 'Lựa chọn trả sau được ghi nhận và chờ đối tác tín dụng xét duyệt.',
            'provider' => 'pay_later_review',
            'initial_status' => 'pending',
            'requires_vietqr' => false,
            'is_simulated' => true,
            'confirmation_title' => 'Yêu cầu trả sau đang chờ xét duyệt.',
            'confirmation_description' => 'Clare đã ghi nhận lựa chọn của bạn. Hệ thống chưa tự duyệt hạn mức hoặc tạo khoản vay.',
        ],
    ],

    'shipping' => [
        'driver' => env('SHIPPING_RATE_DRIVER', 'estimate'),
        'default_option' => env('SHIPPING_DEFAULT_OPTION', 'ghn'),

        'estimate' => [
            'order_cutoff_hour' => (int) env('SHIPPING_ESTIMATE_ORDER_CUTOFF_HOUR', 15),
            'urban_cities' => ['ha noi', 'ho chi minh', 'da nang'],
        ],

        'providers' => [
            'ghn' => [
                'label' => 'Giao Hàng Nhanh (GHN)',
                'service' => 'Tiêu chuẩn',
                'description' => 'Giao tiêu chuẩn, ưu tiên các khu vực nội thành.',
                'base_fee' => 28000,
                'included_weight_grams' => 500,
                'additional_weight_block_grams' => 500,
                'additional_weight_fee' => 5500,
                'outside_urban_area_surcharge' => 12000,
                'urban_estimated_days' => 2,
                'outside_urban_estimated_days' => 4,
            ],
            'ghtk' => [
                'label' => 'Giao Hàng Tiết Kiệm (GHTK)',
                'service' => 'Tiết kiệm',
                'description' => 'Mức phí tiết kiệm cho đơn giao thông thường.',
                'base_fee' => 25000,
                'included_weight_grams' => 500,
                'additional_weight_block_grams' => 500,
                'additional_weight_fee' => 4500,
                'outside_urban_area_surcharge' => 10000,
                'urban_estimated_days' => 3,
                'outside_urban_estimated_days' => 5,
            ],
            'jnt' => [
                'label' => 'J&T Express',
                'service' => 'Tiêu chuẩn',
                'description' => 'Dịch vụ giao tiêu chuẩn của J&T Express.',
                'base_fee' => 32000,
                'included_weight_grams' => 500,
                'additional_weight_block_grams' => 500,
                'additional_weight_fee' => 6000,
                'outside_urban_area_surcharge' => 8000,
                'urban_estimated_days' => 2,
                'outside_urban_estimated_days' => 5,
            ],
        ],
    ],
];
